include:
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

stages:
  - test
  - publish

variables:
  HELM_INSTALL_IMAGE: registry.gitlab.com/gitlab-org/cluster-integration/helm-install-image:helm-3.10.2-kube-1.24.8-alpine-3.15

lint:helm:
  image: $HELM_INSTALL_IMAGE
  script:
    - helm lint

publish:
  stage: publish
  script:
    - curl --request POST
      --form "token=${CHARTS_TRIGGER_TOKEN}"
      --form ref=master
      --form "variables[CHART_NAME]=${CI_PROJECT_NAME}"
      --form "variables[RELEASE_REF]=${CI_COMMIT_REF_NAME}"
      https://gitlab.com/api/v4/projects/2860651/trigger/pipeline
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$/ && $CI_PROJECT_URL == "https://gitlab.com/gitlab-org/charts/gitlab-agent"'
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$/ && $CI_PROJECT_URL == "https://gitlab.com/gitlab-org/security/charts/gitlab-agent"'

.kubectl_create_secret: &kubectl_create_secret
  - kubectl create secret generic test-secret --from-literal=token='FAKE-AGENT-TOKEN'

.helm_repo_setup: &helm_repo_setup
  - helm repo add gitlab https://charts.gitlab.io
  - helm repo update

.local_install_script_token: &local_install_script_token
  - helm install gitlab-agent . --wait --set config.kasAddress='wss://kas.gitlab.test' --set config.token='FAKE-AGENT-TOKEN'

.local_install_script_secret: &local_install_script_secret
  - *kubectl_create_secret
  - helm install gitlab-agent . --wait --set config.kasAddress='wss://kas.gitlab.test' --set config.secretName='test-secret'

.local_upgrade_script: &local_upgrade_script
  - helm upgrade gitlab-agent . --wait --reuse-values

.repo_install_script_token: &repo_install_script_token
  - helm upgrade --install gitlab-agent gitlab/gitlab-agent --wait --set config.kasAddress='wss://kas.gitlab.test' --set config.token='FAKE-AGENT-TOKEN'

.repo_install_script_secret: &repo_install_script_secret
  - helm upgrade --install gitlab-agent gitlab/gitlab-agent --wait --set config.kasAddress='wss://kas.gitlab.test' --set config.secretName='test-secret'

.repo_upgrade_script: &repo_upgrade_script
  - helm upgrade --install gitlab-agent . --wait --reuse-values

test:install:local:token:
  extends: .k3s
  script:
    - *local_install_script_token

test:upgrade:local:token:
  extends: .k3s
  script:
    - *local_install_script_token
    - *local_upgrade_script

test:install:local:secret:
  extends: .k3s
  script:
    - *local_install_script_secret

test:upgrade:local:secret:
  extends: .k3s
  script:
    - *local_install_script_secret
    - *local_upgrade_script

test:upgrade:repo:token:
  extends: .k3s
  script:
    - *helm_repo_setup
    - *repo_install_script_token
    - *repo_upgrade_script

test:upgrade:repo:secret:
  extends: .k3s
  script:
    - *helm_repo_setup
    - *kubectl_create_secret
    - *repo_install_script_secret
    - *repo_upgrade_script

.k3s:
  stage: test
  image: $HELM_INSTALL_IMAGE
  services:
    - name: registry.gitlab.com/gitlab-org/cluster-integration/test-utils/k3s-gitlab-ci/releases/v1.25.0-k3s1
      alias: k3s
  before_script:
    - apk add --update --no-cache curl
    # NOTE: libcurl in the job image is v7.x which is too old for the installed curl v7.x
    - apk upgrade libcurl
    - curl -f k3s:8081 > k3s.yaml
    - export KUBECONFIG=$(pwd)/k3s.yaml
    - kubectl version
    - kubectl cluster-info
