{{- $ocs := .Values.config.operational_container_scanning -}}
{{- if and $ocs.enabled (or (not $ocs.serviceAccount) ($ocs.serviceAccount.create | default true)) -}} 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gitlab-agent.ocs.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "gitlab-agent" }}
  labels:
    {{- include "gitlab-agent.labels" . | nindent 4 }}
  {{- with  ((include "gitlab-agent.ocs.annotations" .) | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
