{{- if or
    .Values.config.token
    (.Values.config.api).jwtPublicKey
    (.Values.config.receptive).enabled
-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-agent.secretName" . }}
  labels:
    {{- include "gitlab-agent.labels" . | nindent 4 }}
data:
  {{- if .Values.config.token }}
  token: {{ .Values.config.token |  b64enc }}
  {{- end }}
  {{- if (.Values.config.api).jwtPublicKey }}
  api-jwt: {{ .Values.config.api.jwtPublicKey | b64enc }}
  {{- end }}
  {{- if (.Values.config.receptive).enabled }}
    {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "gitlab-agent.secretName" .)) | default dict }}
    {{- $secretData := (get $secretObj "data") | default dict }}
    {{- $privateAPIJwt := (get $secretData "private-api-jwt") | default (randAscii 64 | b64enc | b64enc) }}
  private-api-jwt: {{ $privateAPIJwt | quote }}
  {{- end }}
type: Opaque
{{- end }}
